import React from "react";
import { MoveUpRight, Rocket, AudioLines } from "lucide-react";
import BadgeHero from "@/shared/BadgeHero";
import PrimaryButton from "@/shared/PrimaryButton";

export default function HumanlikeQuality() {
  return (
    <section className="py-8 lg:py-16 relative overflow-hidden">
      <div className="container mx-auto px-4 flex flex-col items-center ">
        {/* Top Badge */}
        <BadgeHero
          label="Live demo arena"
          icon={<Rocket className="w-5 h-5 text-yellow-400 fill-yellow-400" />}
        />
        <h1 className="section-title mt-8">Hear the humanlike quality</h1>
        <p>Every voice you hear is generated by our own engine.</p>
        {/* Content Grid */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 w-full max-w-5xl mx-auto mt-14">
          {/* Left Card - Audio Player */}
          <div
            style={{
              background: "#010403D9",
              backdropFilter: "blur(45px)",
            }}
            className="relative group "
          >
            {/* Glow Effect */}
            <div className="absolute -inset-4 bg-purple-600/30 rounded-4xl blur-2xl opacity-50 group-hover:opacity-70 transition-opacity duration-500"></div>

            <div className="relative bg-[#010403D9] rounded-[24px] p-8 h-[400px] flex flex-col items-center justify-between overflow-hidden border border-white/5 shadow-2xl">
              {/* Save & Play Button */}
              <div className="w-full flex justify-end">
                <button className="bg-[#FFFFFF12] hover:bg-[#444] text-white/90 px-4 py-1.5 rounded-full text-sm font-medium transition-colors cursor-pointer">
                  Save & play
                </button>
              </div>

              {/* Central Audio Visual */}
              <div className="relative">
                <div className="absolute inset-0 bg-linear-to-tr from-blue-500 to-purple-500 rounded-full blur-xl opacity-40 animate-pulse"></div>
                <div className="w-32 h-32 rounded-full border-12px border-[#2A2A2A] flex items-center justify-center relative z-10 bg-[#151515] overflow-hidden">
                  <div className="absolute inset-0 bg-linear-to-t from-blue-500/20 to-transparent"></div>
                  <AudioLines className="w-10 h-10 text-white" />
                </div>
                {/* Ring Gradient */}
                <div className="absolute inset-0 rounded-full border-2 border-transparent bg-linear-to-b from-purple-500/50 to-blue-500/50 [mask:linear-gradient(#fff_0_0)_content-box,linear-gradient(#fff_0_0)] z-0"></div>
              </div>

              {/* Track Info */}
              <div className="text-center space-y-1">
                <h3 className="text-white text-xl font-medium">DE - German</h3>
                <p className="text-gray-500 text-sm">Recording...</p>
              </div>
            </div>
          </div>

          {/* Right Card - Transcript */}
          <div
            style={{
              background:
                "linear-gradient(304.65deg, rgba(255, 255, 255, 0.05) 13.81%, rgba(153, 153, 153, 0.0332332) 33.55%, rgba(153, 153, 153, 0.0125) 81.13%)",
              backdropFilter: "blur(45px)",
            }}
            className="rounded-[24px] p-8 h-[400px] border-[0.5px] border-[#999999]/30 shadow-sm relative overflow-hidden"
          >
            <div className="h-full overflow-y-auto pr-4 custom-scrollbar space-y-6">
              <p className="text-gray-300 font-medium text-lg ">
                Hi, this is a call in German.
              </p>
              <p className="text-gray-300 font-medium text-lg ">
                Hallo, ich möchte meine gesprochenen Wörter in Textform
                übernehmen,
              </p>
              <p className="text-gray-200 font-medium text-lg/relaxed">
                wobei ich großen Wert auf die korrekte Aussprache und den
                richtigen Style liege.
              </p>
              <p className="text-gray-200 font-medium text-lg/relaxed">
                In diesem Zusammenhang ist Spiralink ein äußerst hilfreiches
                Tool, das nicht nur Deutsch unterstützt, sondern auch eine
                Vielzahl von Sprachen und Akzente.
              </p>
              <p className="text-gray-200 font-medium text-lg/relaxed">
                Es ermöglicht mir, meine Sprachfähigkeiten zu verbessern und
                sicherzustellen, dass meine Botschaft klar und authentisch
                rüberkommt.
              </p>
            </div>
          </div>
        </div>

        {/* Bottom Link */}
        <div className="pt-10">
          <PrimaryButton
            label="See All Voice Personas"
            className="w-full lg:w-auto"
          />
        </div>
      </div>
    </section>
  );
}
